# Generated by Django 2.2.9 on 2020-03-17 07:55

from django.db import migrations, models
import mysite.utils


class Migration(migrations.Migration):

    dependencies = [
        ('thumb_page', '0006_auto_20200317_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='king_class',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=mysite.utils.uuid_upload_to),
        ),
    ]
